// <auto-generated />
using System;
using Maliev.CareerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.CareerService.Data.Migrations
{
    [DbContext(typeof(CareerDbContext))]
    [Migration("20251106133350_AddRowVersionDefaultValue")]
    partial class AddRowVersionDefaultValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.CareerService.Data.Models.ApplicationStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("from_status");

                    b.Property<bool>("IsReversal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reversal");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReversedChangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversed_change_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("idx_status_changes_application");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("idx_status_changes_changed_at");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("idx_status_changes_changed_by");

                    b.ToTable("application_status_changes", (string)null);
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.ELearningResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<string>("ExternalLmsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_lms_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ResourceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource_code");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resource_type");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("'\\x00000000000000000001'::bytea");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_elearning_resources_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_elearning_resources_is_active");

                    b.HasIndex("ResourceCode")
                        .IsUnique()
                        .HasDatabaseName("uq_elearning_resources_resource_code");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("ix_elearning_resources_resource_type");

                    b.ToTable("elearning_resources", null, t =>
                        {
                            t.HasCheckConstraint("chk_elearning_resources_estimated_minutes_positive", "estimated_minutes IS NULL OR estimated_minutes > 0");
                        });
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.EmployeeDevelopmentGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionItems")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("action_items");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("GoalDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("goal_description");

                    b.Property<string>("GoalTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("goal_title");

                    b.Property<Guid>("IdpId")
                        .HasColumnType("uuid")
                        .HasColumnName("idp_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ProgressNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("progress_notes");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("'\\x00000000000000000001'::bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IdpId")
                        .HasDatabaseName("i_x_employee_development_goals_idp_id");

                    b.HasIndex("TargetDate");

                    b.HasIndex("IdpId", "Status")
                        .HasDatabaseName("ix_employee_development_goals_idp_id_status");

                    b.ToTable("employee_development_goals", (string)null);
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.EmployeeTrainingEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("completion_notes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<string>("EnrollmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("enrollment_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("MarkedCompleteBy")
                        .HasColumnType("uuid")
                        .HasColumnName("marked_complete_by");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("'\\x00000000000000000001'::bytea");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TrainingProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_program_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_training_enrollments_employee_id");

                    b.HasIndex("EnrolledAt")
                        .HasDatabaseName("ix_employee_training_enrollments_enrolled_at");

                    b.HasIndex("EnrollmentType")
                        .HasDatabaseName("ix_employee_training_enrollments_enrollment_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_employee_training_enrollments_status");

                    b.HasIndex("TrainingProgramId")
                        .HasDatabaseName("ix_employee_training_enrollments_training_program_id");

                    b.HasIndex("TrainingProgramId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("uq_employee_training_enrollments_program_employee");

                    b.ToTable("employee_training_enrollments", null, t =>
                        {
                            t.HasCheckConstraint("chk_employee_training_enrollments_dates", "completed_at IS NULL OR started_at IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.IndividualDevelopmentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("PlanYear")
                        .HasColumnType("integer")
                        .HasColumnName("plan_year");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("'\\x00000000000000000001'::bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Status");

                    b.HasIndex("EmployeeId", "PlanYear")
                        .IsUnique()
                        .HasDatabaseName("ix_individual_development_plans_employee_id_plan_year_unique");

                    b.ToTable("individual_development_plans", (string)null);
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<Guid[]>("AdditionalFileIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("additional_file_ids");

                    b.Property<string>("ApplicantCountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("applicant_country_code");

                    b.Property<string>("ApplicantEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("applicant_email");

                    b.Property<string>("ApplicantFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("applicant_first_name");

                    b.Property<string>("ApplicantLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("applicant_last_name");

                    b.Property<string>("ApplicantPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("applicant_phone");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text")
                        .HasColumnName("cover_letter");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_posting_id");

                    b.Property<Guid>("ResumeFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_file_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("'\\x00000000000000000001'::bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantEmail")
                        .HasDatabaseName("idx_job_applications_email");

                    b.HasIndex("AppliedAt")
                        .HasDatabaseName("idx_job_applications_applied");

                    b.HasIndex("JobPostingId")
                        .HasDatabaseName("idx_job_applications_posting");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_job_applications_status");

                    b.HasIndex("JobPostingId", "ApplicantEmail")
                        .IsUnique()
                        .HasDatabaseName("uq_job_applications_posting_email");

                    b.ToTable("job_applications", (string)null);
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("application_deadline");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employment_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position_code");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position_title");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("responsibilities");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("'\\x00000000000000000001'::bytea");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salary_max");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salary_min");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDeadline")
                        .HasDatabaseName("idx_job_postings_deadline");

                    b.HasIndex("Department")
                        .HasDatabaseName("idx_job_postings_department");

                    b.HasIndex("EmploymentType")
                        .HasDatabaseName("idx_job_postings_employment_type");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_job_postings_active");

                    b.HasIndex("PositionCode")
                        .IsUnique()
                        .HasDatabaseName("uq_job_postings_position_code");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("idx_job_postings_published");

                    b.HasIndex("IsActive", "PublishedAt", "ApplicationDeadline")
                        .HasDatabaseName("idx_job_postings_active_list");

                    b.ToTable("job_postings", null, t =>
                        {
                            t.HasCheckConstraint("chk_job_postings_deadline_future", "application_deadline > created_at");

                            t.HasCheckConstraint("chk_job_postings_salary_range", "salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max");
                        });
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.TrainingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("DurationHours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("duration_hours");

                    b.Property<string>("ExternalLmsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_lms_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mandatory");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("program_code");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("program_name");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("'\\x00000000000000000001'::bytea");

                    b.PrimitiveCollection<string[]>("TargetRoles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("target_roles");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_training_programs_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_training_programs_is_active");

                    b.HasIndex("IsMandatory")
                        .HasDatabaseName("ix_training_programs_is_mandatory");

                    b.HasIndex("ProgramCode")
                        .IsUnique()
                        .HasDatabaseName("uq_training_programs_program_code");

                    b.ToTable("training_programs", null, t =>
                        {
                            t.HasCheckConstraint("chk_training_programs_duration_positive", "duration_hours > 0");
                        });
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.ApplicationStatusChange", b =>
                {
                    b.HasOne("Maliev.CareerService.Data.Models.JobApplication", "Application")
                        .WithMany("StatusChanges")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_application_status_changes__job_applications_application_id");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.EmployeeDevelopmentGoal", b =>
                {
                    b.HasOne("Maliev.CareerService.Data.Models.IndividualDevelopmentPlan", "Idp")
                        .WithMany("Goals")
                        .HasForeignKey("IdpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_employee_development_goals__individual_development_plans_idp_id");

                    b.Navigation("Idp");
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.EmployeeTrainingEnrollment", b =>
                {
                    b.HasOne("Maliev.CareerService.Data.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_employee_training_enrollments__training_programs_training_pro~");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.JobApplication", b =>
                {
                    b.HasOne("Maliev.CareerService.Data.Models.JobPosting", "JobPosting")
                        .WithMany("Applications")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_job_applications__job_postings_job_posting_id");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.IndividualDevelopmentPlan", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.JobApplication", b =>
                {
                    b.Navigation("StatusChanges");
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.JobPosting", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Maliev.CareerService.Data.Models.TrainingProgram", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
